### ISSUE TITLE
error when loading extension to Burp v2.0.11beta

### ISSUE THREAD

**Issue by ghost** [AresS31/flarequench#1]
java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.a3_.a(Unknown Source)
	at burp.a3_.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by aress31** [comment]
The jar file file available in the release sections is compiled using OracleJDK 11. If you need to compile the code using any other version of Java please follow the instructions on the README.
